version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.1
    resource_class: large
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: ['.']
      - run: 
          name: packerinstall
          command: |
            sh ./scripts/packer.sh
          no_output_timeout: 30m
      - run:
          name: packer
          command: |
            PACKER_LOG=1 packer init ./centos/centos7.pkr.hcl
          no_output_timeout: 30m
      - run:
          name: packer
          command: |
            PACKER_LOG=1 packer build ./centos/centos7.pkr.hcl
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build


