version: 2
jobs:
  validate:
    docker:
      - image: centos:centos7
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: ['.']

  build-base:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: packerplugin
          command: |
            packer init ./centos/init.json 
          no_output_timeout: 30m
      - run:
          name: packer
          command: |
            packer build ./centos/qemu.json
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate

