version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths: ['.']
      - run: 
          name: packerinstall
          command: |
            sh ./scripts/packer.sh
          no_output_timeout: 30m
      - run:
          name: packer
          command: |
            PACKER_LOG=1 packer build ./centos/centos9.pkr.hcl
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build


